services:
  db:
    image: mariadb:10.6
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD}: ${MYSQL_PASSWORD}
    restart: always

  app:
    image: nextcloud:latest
    depends_on:
      - db
    volumes:
      - ./nextcloud_config:/var/www/html
      - < Your external drive mount point >:/nextcloud/data
    restart: always
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD}: ${MYSQL_PASSWORD}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES}
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_TRUSTED_DOMAINS}

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: always
  noip:
    image: ghcr.io/noipcom/noip-duc:latest
    environment:
      NOIP_USERNAME: ${NOIP_USERNAME}
      NOIP_PASSWORD}: ${NOIP_PASSWORD}
      NOIP_HOSTNAMES: ${NOIP_HOSTNAMES}
      NOIP_CHECK_INTERVAL: ${NOIP_CHECK_INTERVAL}
    restart: always